spring:
  cloud:
    polaris:
      discovery:
        enabled: true

    gateway:
      routes:
        - id: macula-example-consumer
          uri: lb://macula-example-tencent-consumer
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: e4da4a32-592b-46f0-ae1d-784310e88423
          client-secret: secret
          introspection-uri: http://127.0.0.1:9010/oauth2/introspect

macula:
  gateway:
    security:
      only-auth-urls: /api/**

logging:
  level:
    root: info
    dev.macula.example.gateway: debug
    dev.macula.boot.starter.cloud.gateway: debug
  file:
    name: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  #config: classpath:logback-skywalking.xml